#!/bin/bash

cd $(dirname $0)

# Ask user whether to copy the files from the frappe_docker repository
read -p "copy the files from the frappe_docker repository before? (y/N) " -r response
if [ "$response" == "y" ]; then
    cp -R ../../frappe_docker/development .
    cp -R ../../frappe_docker/images/production/Containerfile .
    cp -R ../../frappe_docker/resources .
    cp -R ../../frappe_docker/devcontainer-example/* .
    cp -R development/vscode-example development/.vscode
    echo "Now check the changes in the files and folders in the .devcontainer folder and the Dockerfile."
else
    echo "No files copied."
fi

echo "### DO NOT EDIT THIS FILE. IT IS GENERATED AUTOMATICALLY. ###" > Dockerfile
echo "### Make changes only in Dockerfile.devcontainer          ###" >> Dockerfile
echo "" >> Dockerfile
cat Containerfile >> Dockerfile
echo "" >> Dockerfile
cat Dockerfile.devcontainer >> Dockerfile
echo "Dockerfile updated."